services:
    app:
      build: .
      ports:
        - "8000:8000"  # Expose the app on port 8000 or any other port
      environment:
        - SLACK_BOT_TOKEN= # enter the slakc bot token
        - SLACK_SIGNING_SECRET= # enter the slack signing secret
        - SLACK_APP_TOKEN= # enter the slack app token
        - REDIS_HOST=redis  # Use the service name `redis` as the hostname for connecting
      depends_on:
        - redis
  
    redis:
      image: redis:alpine
